# Generated by Django 5.2.15 on 2026-06-10 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='不可猜測的唯一識別碼（UUID4）', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Worker 自報的唯一名稱，e.g. 'worker-taipei-01'", max_length=128, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Worker 的可達 IP 位址（IPv4 或 IPv6）')),
                ('port', models.PositiveIntegerField(default=8100, help_text='Worker Agent 監聽的 Port')),
                ('status', models.CharField(choices=[('online', '在線可用'), ('busy', '執行中'), ('offline', '離線'), ('draining', '排水中（不接新任務）')], db_index=True, default='offline', help_text='節點目前狀態', max_length=16)),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='支援的壓測引擎清單，e.g. ["k6", "jmeter"]')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='Worker 最後一次心跳的 UTC 時間', null=True)),
                ('resource_snapshot', models.JSONField(blank=True, default=dict, help_text='最新資源使用率快照 {cpu_pct, mem_pct, disk_pct}')),
                ('active_task_count', models.PositiveIntegerField(default=0, help_text='目前正在執行的任務數量')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Worker 節點',
                'verbose_name_plural': 'Worker 節點',
                'ordering': ['-last_heartbeat_at'],
            },
        ),
    ]
