# Generated by Django 5.2.15 on 2026-06-10 03:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadTestTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='任務唯一識別碼（UUID4）', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="任務友善名稱，e.g. 'Sprint-42 壓測'", max_length=256)),
                ('engine', models.CharField(choices=[('k6', 'k6'), ('jmeter', 'JMeter'), ('loadrunner', 'LoadRunner')], db_index=True, help_text='使用的壓測引擎', max_length=16)),
                ('script_path', models.CharField(help_text="腳本相對路徑，e.g. 'k6/stress_cpu.js'", max_length=512)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='動態引擎參數字典，e.g. {"TARGET_URL": "http://..."}')),
                ('target_url', models.URLField(help_text='靶機 Base URL，e.g. http://localhost:8000', max_length=512)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='預計執行時間；null 表示立即執行', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Celery Worker 實際開始執行時間', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='任務結束時間（成功或失敗）', null=True)),
                ('status', models.CharField(choices=[('pending', '待派發'), ('scheduled', '已排程'), ('dispatched', '已派發至 Worker'), ('running', '執行中'), ('completed', '已完成'), ('failed', '失敗'), ('cancelled', '已取消')], db_index=True, default='pending', help_text='任務目前狀態（7 態狀態機）', max_length=16)),
                ('error_message', models.TextField(blank=True, default='', help_text='失敗原因摘要；成功時為空字串')),
                ('created_by', models.CharField(blank=True, help_text='建立者識別（Phase 3 MVP 先用字串，後續整合 Auth）', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(blank=True, help_text='執行節點；完成後保留歷史，不隨 Worker 刪除而消失', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workers.workernode')),
            ],
            options={
                'verbose_name': '壓測任務',
                'verbose_name_plural': '壓測任務',
                'ordering': ['-created_at'],
            },
        ),
    ]
