# Generated by Django 5.2.15 on 2026-06-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadtesttask',
            name='target_url',
            field=models.CharField(help_text='靶機 Base URL，e.g. http://localhost:8000', max_length=512),
        ),
    ]
